name: Repository maintenance
on:
  workflow_call:
    inputs:
      CLEAN:
        description: "Clean unused images"
        required: false
        default: true
        type: boolean
      DRY_RUN:
        description: "Dry run"
        required: false
        default: false
        type: boolean
      BRANCH:
        type: string
        description: 'Branch to push changes to'
        required: false
        default: 'main'
    secrets:
      GH_PAT:
        required: true
      author_email:
        required: false
        description: "The author email"
      author_name:
        required: false
        description: "The author name"
jobs:
  unused_images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
        cache: pipenv
    - name: Clean
      if: inputs.CLEAN
      run: |
       echo "Cleaning"
       pipenv install pyyaml
       pipenv run python .github/find_unused_image.py
    - name: Commit
      if: inputs.CLEAN && inputs.DRY_RUN == false
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN}}
        author_email: ${{ secrets.AUTHOR_EMAIL || 'github-actions[bot]@users.noreply.github.com' }}
        author_name: ${{ secrets.AUTHOR_NAME || 'github-actions[bot]' }}
        branch: ${{ inputs.BRANCH }}
